#!/usr/bin/env python3
import sys


def factors():
    with  open(str(sys.argv[1]), 'r') as file:
        for number in file:
            for i in range(2, int(number)+1):
                if int(number) % i == 0:
                    print("{}={}*{}".format(int(number), (int(number)//i), i))
                    break
factors()
